### ISSUE TITLE
Stopped updating

### ISSUE THREAD

**Issue by Transisto** [sipa/bitcoin-stats#7]
Stopped updating about a week ago.

**Comment by adlai** [comment]
On [2021-06-22, Transisto wrote](https://github.com/sipa/bitcoin-stats/issues/7#issue-950234333):
> Stopped updating about a week ago.

... and started again, and stopped again.

Fortunately, the code does not rot quickly; however, `ibd` takes quite long, and that's before anyone even touches `git clone` !

Any hope of someone power cycling the relevant cloudbank, @sipa ?

**Comment by sipa** [comment]
@adlai Thanks, should be fixed now.
